
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.8.0-browsers
    working_directory: ~/mQuery
    steps:
      - checkout
      - run:
          name: Installing dependencies...
          command: |
            sudo apt install -y node-typescript && \
            sudo npm install -g uglify-js && \
            npm i --only=dev
      - run:
          name: Building mQuery...
          command: |
            bash ./build.sh && \
            node ./test/test.js
      - run:
          name: Testing...
          command: |
            node ./test/test.js