
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.8.0-browsers
    working_directory: ~/mQuery
    steps:
      - checkout
      - run:
          name: Installing node typescript tools and yarn...
          command: |
            sudo apt install -y node-typescript && \
            sudo npm install -g uglify-js yarn
      - run:
          name: Building mQuery...
          command: |
            cd ~/mQuery && bash ./build.sh && node ./test/test.js